### ISSUE TITLE
for some future build instructions

### ISSUE THREAD

**Issue by LeaseOnLife** [keesverruijt/mayara#1]
as of 20240818: on a x64 Debian Sid system:
it builds with rust 1.80.1 (when rust is installed as per https://www.rust-lang.org/learn/get-started)
it fails to build with rust 1.79.0 (included in Debian SID) with error message "cannot find function `size_of` in this scope"...

I am new to rust, and I am hoping to follow along the progress of this project, and thereby get some exposure to rust.

**Comment by keesverruijt** [comment]
I'm developing with 1.80.1, I will update the version requirements in the `Cargo.toml` file.
